### ISSUE TITLE
Declared type gets transformed to void

### ISSUE THREAD

**Issue by Elliot67** [antfu/webext-bridge#16]
> Tested with [vitesse-webext](https://github.com/antfu/vitesse-webext) template. Not sure if the issue comes from the template or this repo.

When any Manifest.___ interface is declared as a return type,  typescript changes it with a void type inside `onMessage` and `sendMessage` functions.

```ts
// shim.d.ts
import { ProtocolWithReturn } from 'webext-bridge'
import { Manifest } from 'webextension-polyfill'

declare module 'webext-bridge' {
  export interface ProtocolMap {
    'get-manifest': ProtocolWithReturn<null, Manifest.WebExtensionManifest>
  }
}

```

```ts
// In background script
onMessage('get-manifest', () => {
  return browser.runtime.getManifest() // Which return Manifest.WebExtensionManifest
})
/* IDE: Argument of type '() => Manifest.WebExtensionManifest' is not assignable to parameter of type 'OnMessageCallback<null, void>'.
  Type 'WebExtensionManifest' is not assignable to type 'void | Promise<void>'.
    Type 'WebExtensionManifest' is missing the following properties from type 'Promise<void>': then, catch, finally, [Symbol.toStringTag]*/
```

```ts
// In option page
const manifest = await sendMessage('get-manifest', null, 'background');
// IDE: manifest: void
```

**Comment by samrum** [comment]
I'm running into this same issue when using any `interface`. If I make the definition a `type` it works.
Not sure if there's some TypeScript concept at work I'm not familiar with or if it's an issue with the lib.

**Comment by Elliot67** [comment]
Sorry to bother you @antfu, can you release the fix when you have some time ?

Your work is really appreciated !
