### ISSUE TITLE
Send a message to 'content-script@<tab>' but only to a frame

### ISSUE THREAD

**Issue by charlie632** [antfu/webext-bridge#2]
The page I'm working on has several frames (iframes), so I would like to send a message to just one specific frame, something like:

```
const returnData = await sendMessage('bar', { /* ... */ }, 'content-script@175.1') // tab 175, frameId: 1
```

Is it possible right now? If not, I can happily help with a PR for that :)

**Comment by antfu** [comment]
Not sure. How could you specify the id of the iframe? If you can find a solution, PR will be greatly welcome :)

**Comment by charlie632** [comment]
@antfu I opened this one long ago, but now I'm more confident with web extension APIs so I created a PR for this specific problem. https://github.com/antfu/webext-bridge/pull/13

LMK what you think!
